dist: bionic

env:
  global:
    - REGISTRY_URL: "docker.io"  # registry.gitlab.com
    - REPOSITORY: "${REGISTRY_URL}/${TRAVIS_REPO_SLUG}"

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "${REPOSITORY}:${CI_JOB_NAME}"
                   -f "docker_base/Dockerfile"
                   "docker_base"
      - docker push "${REPOSITORY}"
