language: minimal

dist: bionic

env:
  global:
    - REGISTRY_URL: "docker.io"  # docker.io or other registry URL, DOCKER_REGISTRY_USER/DOCKER_REGISTRY_PASSWORD to be set in CI env.
    - DOCKER_BUILDKIT: 1

install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json && sudo service docker restart && docker info

before_script:
  - echo IP=$(curl -s http://ifconfig.me/ip)
  - CI_PROJECT_NAMESPACE=$([[ "$TRAVIS_PULL_REQUEST_SLUG" = "" ]] && echo "$(dirname ${TRAVIS_REPO_SLUG})" || echo "$(dirname ${TRAVIS_PULL_REQUEST_SLUG})")
  - export NAMESPACE=$(echo "${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}" | awk '{print tolower($0)}')
  - build_image() {
      IMG=$1; TAG=$2; FILE=$3; shift 3;
      if [ "$TRAVIS_BRANCH" != "master" ] ; then
        IMG="${IMG}-${TRAVIS_BRANCH}" ;
      fi ;
      REPOSITORY="${NAMESPACE}/${IMG}" ;
      docker build --squash --compress --force-rm=true -t "${REPOSITORY}:${TAG}" -f "$FILE" --build-arg "BASE_REPO=${REPOSITORY}" "$@" "$(dirname $FILE)" ;
    }
  - alias_image() {
      IMG_1=$1; TAG_1=$2; IMG_2=$3; TAG_2=$4; shift 4;
      if [ "$TRAVIS_BRANCH" != "master" ] ; then
        IMG_1="${IMG_1}-${TRAVIS_BRANCH}" ; IMG_2="${IMG_2}-${TRAVIS_BRANCH}" ;
      fi ;
      docker tag "${NAMESPACE}/${IMG_1}:${TAG_1}" "${NAMESPACE}/${IMG_2}:${TAG_2}" ;
    }
  - VER() { echo `date +%Y.%m%d` ; }

after_script:
  - docker image prune --force && docker images
  - IMGS=$(docker images | grep "second" | awk '{print $1 ":" $2}')
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
      echo "$DOCKER_REGISTRY_PASSWORD" | docker login "${REGISTRY_URL}" -u "$DOCKER_REGISTRY_USER" --password-stdin ;
      for IMG in $(echo $IMGS | tr " " "\n") ;
      do
        docker push "${IMG}";
        status=$?;
        echo "[${status}] Image pushed > ${IMG}";
      done
    else
      echo "Not pushing ${IMGS} in PR ...";
    fi

stages: [atom, base, core, dev, cuda]

jobs:
  allow_failures:
    - name: "cuda_10.2"
    - name: "cuda_11.0"

  include:
    - name: atom
      stage: atom
      script: build_image atom VER docker_atom/Dockerfile

    - name: base
      stage: base
      script:
        - export DATE=`date +%Y.%m%d`
        - build_image base VER docker_base/Dockerfile
        - alias_image base VER py-mini VER

#-------------------------------------------------------------------------------
# Python: (mini - same as `base` as aliased above), datascience, bioinfo, nlp, cv, full
#-------------------------------------------------------------------------------
    - name: py-data
      stage: core
      script: build_image py-data VER docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database"

    - name: py-bioinfo
      stage: core
      script: build_image py-bio  VER docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,bioinfo"

    - name: py-nlp
      stage: core
      script: build_image py-nlp  VER docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,nlp"

    - name: py-cv
      stage: core
      script: build_image py-cv   VER docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,cv"

    - name: py-std
      stage: core
      script: build_image py-std  VER docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database,nlp,cv,bioinfo"

    - name: py-jdk
      stage: base
      script: build_image py-jdk  VER docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database,nlp,cv,bioinfo" --build-arg "ARG_PROFILE_JAVA=base"
#-------------------------------------------------------------------------------
#    R: mini, std, latex, studio
#-------------------------------------------------------------------------------
    - name: r-mini
      stage: core
      script: build_image r-mini  VER docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base"

    - name: r-std
      stage: core
      script: build_image r-std   VER docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience" --build-arg "ARG_PROFILE_JAVA=base"

    - name: r-latex
      stage: core
      script: build_image r-latex VER docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience" --build-arg "ARG_PROFILE_JAVA=base" --build-arg "ARG_PROFILE_LATEX=base,cjk"

    - name: r-full
      stage: core
      script: build_image r-full  VER docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" --build-arg "ARG_PROFILE_JAVA=base" --build-arg "ARG_PROFILE_LATEX=base,cjk"
#-------------------------------------------------------------------------------
#    NodeJS: base
#-------------------------------------------------------------------------------
    - name: node
      stage: core
      script: build_image node    VER docker_core/Dockerfile --build-arg "ARG_PROFILE_NODEJS=base"
#-------------------------------------------------------------------------------
#    Java: base
#-------------------------------------------------------------------------------
    - name: jdk
      stage: core
      script: build_image jdk     VER docker_core/Dockerfile --build-arg "ARG_PROFILE_JAVA=base"
#-------------------------------------------------------------------------------
#    Julia: base
#-------------------------------------------------------------------------------
    - name: julia
      stage: core
      script: build_image julia   VER docker_core/Dockerfile --build-arg "ARG_PROFILE_JULIA=base"
#-------------------------------------------------------------------------------
#    Go: base
#-------------------------------------------------------------------------------
    - name: go
      stage: core
      script: build_image go      VER docker_core/Dockerfile --build-arg "ARG_PROFILE_GO=base"
#-------------------------------------------------------------------------------
#    core: mini
#-------------------------------------------------------------------------------
    # - name: octave
    #   stage: fabric
    #   script: build_image octave  VER   docker_core/Dockerfile --build-arg "ARG_PROFILE_OCTAVE=base"
#-------------------------------------------------------------------------------
#    core: full
#-------------------------------------------------------------------------------
    - name: core
      stage: core
      script: build_image core    VER docker_core/Dockerfile        
              --build-arg "ARG_PROFILE_PYTHON=base"
              --build-arg "ARG_PROFILE_R=base"                
              --build-arg "ARG_PROFILE_JAVA=base"
              --build-arg "ARG_PROFILE_GO=base"
              --build-arg "ARG_PROFILE_JULIA=base"

#-------------------------------------------------------------------------------
#    dev
#-------------------------------------------------------------------------------
    - name: dev
      stage: dev
      script: build_image dev docker_dev/Dockerfile
              --build-arg "ARG_PROFILE_JUPYTER=base,kernels,extensions"
              --build-arg "ARG_PROFILE_VSCODE=base"

#===============================================================================
# GPU: cuda_10.0, cuda_10.1, cuda_10.2 (cuda), cuda_11.0
#-------------------------------------------------------------------------------
    - name: cuda_10.0
      stage: cuda
      script: build_image cuda cuda_10.0 docker_cuda/cuda10.0.Dockerfile

    - name: cuda_10.1
      stage: cuda
      script: build_image cuda cuda_10.1 docker_cuda/cuda10.1.Dockerfile

    - name: cuda_10.2
      stage: cuda
      script: build_image cuda cuda_10.2 docker_cuda/cuda10.2.Dockerfile && alias_image qpod cuda_10.2 cuda

    - name: cuda_11.0
      stage: cuda
      script: build_image cuda cuda_11.0 docker_cuda/cuda11.0.Dockerfile


notifications:
  slack: q-pod:lrzKf5Ff1Ao1MGclzElR23j4
