dist: bionic

env:
  global:
    - REGISTRY_URL: "docker.io"  # or other registry URL
    - REPOSITORY: $(dirname ${TRAVIS_REPO_SLUG}")/qpod

before_script:
    - cat /proc/meminfo | grep MemTotal
    - free -m
    - df -h
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin

jobs:
  include:
    - name: "base"
      stage: base
      script:
        - docker build -t "${REPOSITORY}:${TRAVIS_JOB_NAME}"
                       -f "docker_base/Dockerfile" "docker_base"
        - docker push "${REPOSITORY}"
