language: minimal

dist: bionic

env:
  global:
    - REGISTRY_URL: "docker.io"  # docker.io or other registry URL, DOCKER_REGISTRY_USER/DOCKER_REGISTRY_PASSWORD to be set in CI env.

install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json && sudo service docker restart && docker info

before_script:
  - echo IP=$(curl -s http://ifconfig.me/ip)
  - CI_PROJECT_NAMESPACE=$([[ "$TRAVIS_PULL_REQUEST_SLUG" = "" ]] && echo "$(dirname ${TRAVIS_REPO_SLUG})" || echo "$(dirname ${TRAVIS_PULL_REQUEST_SLUG})")
  - export NAMESPACE=$(echo "${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}" | awk '{print tolower($0)}')
  - build_image() {
      IMG=$1; TAG=$2; FILE=$3; shift 3;
      if [ "$TRAVIS_BRANCH" != "master" ] ; then
        IMG="${IMG}-${TRAVIS_BRANCH}" ;
      fi ;
      REPOSITORY="${NAMESPACE}/${IMG}" ;
      docker build --squash --force-rm=true -t "${REPOSITORY}:${TAG}" -f "$FILE" --build-arg "BASE_REPO=${REPOSITORY}" "$@" "$(dirname $FILE)" ;
    }
  - alias_image() {
      IMG=$1; TAG_OLD=$2; TAG_NEW=$3; shift 3;
      if [ "$TRAVIS_BRANCH" != "master" ] ; then
        IMG="${IMG}-${TRAVIS_BRANCH}" ;
      fi ;
      docker tag "${NAMESPACE}/${IMG}:${TAG_OLD}" "${NAMESPACE}/${IMG}:${TAG_NEW}" ;
    }

after_script:
  - docker image prune --force && docker images
  - IMGS=$(docker images | grep "second" | awk '{print $1 ":" $2}')
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
      echo "$DOCKER_REGISTRY_PASSWORD" | docker login "${REGISTRY_URL}" -u "$DOCKER_REGISTRY_USER" --password-stdin ;
      for IMG in $(echo $IMGS | tr " " "\n") ;
      do
        docker push "${IMG}";
        status=$?;
        echo "[${status}] Image pushed > ${IMG}";
      done
    else
      echo "Not pushing ${IMGS} in PR ...";
    fi

stages:
  - base
  - core
  - fabric
  - ide
  - cuda

jobs:
  allow_failures:
    - name: "cuda_10.2"
    - name: "cuda_11.0"

  include:
    - name: base
      stage: base
      script: build_image qpod base docker_base/Dockerfile

    - name: core
      stage: core
      script: build_image qpod core docker_core/Dockerfile && alias_image qpod core py


#-------------------------------------------------------------------------------
# Python: (mini - same as core as aliased above), datascience, bioinfo, nlp, cv, full
#-------------------------------------------------------------------------------
    - name: py-data
      stage: fabric
      script: build_image qpod py-data    docker_fabric/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database"

    - name: py-bioinfo
      stage: fabric
      script: build_image qpod py-bioinfo docker_fabric/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,bioinfo"

    - name: py-nlp
      stage: fabric
      script: build_image qpod py-nlp     docker_fabric/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,nlp"

    - name: py-cv
      stage: fabric
      script: build_image qpod py-cv      docker_fabric/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,cv"

    - name: py-full
      stage: fabric
      script: build_image qpod py-full    docker_fabric/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database,nlp,cv,bioinfo"

#-------------------------------------------------------------------------------
#    R: base, full
#-------------------------------------------------------------------------------
    - name: r
      stage: fabric
      script: build_image qpod r          docker_fabric/Dockerfile --build-arg "ARG_PROFILE_R=base"

    - name: r-full
      stage: fabric
      script: build_image qpod r-full     docker_fabric/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" --build-arg "ARG_PROFILE_LATEX=base,cjk"

#-------------------------------------------------------------------------------
#    NodeJS: base
#-------------------------------------------------------------------------------
    - name: node
      stage: fabric
      script: build_image qpod node       docker_fabric/Dockerfile --build-arg "ARG_PROFILE_NODEJS=base"
#-------------------------------------------------------------------------------
#    Java: base
#-------------------------------------------------------------------------------
    - name: java
      stage: fabric
      script: build_image qpod java       docker_fabric/Dockerfile --build-arg "ARG_PROFILE_JAVA=base"
#-------------------------------------------------------------------------------
#    Julia: base
#-------------------------------------------------------------------------------
    - name: julia
      stage: fabric
      script: build_image qpod julia      docker_fabric/Dockerfile --build-arg "ARG_PROFILE_JULIA=base"
#-------------------------------------------------------------------------------
#    Go: base
#-------------------------------------------------------------------------------
    - name: go
      stage: fabric
      script: build_image qpod go         docker_fabric/Dockerfile --build-arg "ARG_PROFILE_GO=base"
#-------------------------------------------------------------------------------
#    Octave: mini
#-------------------------------------------------------------------------------
    # - name: octave
    #   stage: fabric
    #   script: build_image qpod octave     docker_fabric/Dockerfile --build-arg "ARG_PROFILE_OCTAVE=base"
#-------------------------------------------------------------------------------
#    fabric-full
#-------------------------------------------------------------------------------
    - name: fabric-full
      stage: fabric
      script: build_image qpod fabric-full docker_fabric/Dockerfile        
              --build-arg "ARG_PROFILE_PYTHON=base"
              --build-arg "ARG_PROFILE_R=base"                
              --build-arg "ARG_PROFILE_JAVA=base"
              --build-arg "ARG_PROFILE_GO=base"
              --build-arg "ARG_PROFILE_JULIA=base"

#-------------------------------------------------------------------------------
#    IDE
#-------------------------------------------------------------------------------
    - name: full
      stage: ide
      script: build_image qpod full docker_ide/Dockerfile        
              --build-arg "ARG_PROFILE_JUPYTER=base,kernels,extensions"
              --build-arg "ARG_PROFILE_VSCODE=base"

#===============================================================================
# GPU: cuda_10.0, cuda_10.1, cuda_10.2 (cuda), cuda_11.0
#-------------------------------------------------------------------------------
    - name: cuda_10.0
      stage: cuda
      script: build_image qpod cuda_10.0 docker_cuda/cuda10.0.Dockerfile

    - name: cuda_10.1
      stage: cuda
      script: build_image qpod cuda_10.1 docker_cuda/cuda10.1.Dockerfile

    - name: cuda_10.2
      stage: cuda
      script: build_image qpod cuda_10.2 docker_cuda/cuda10.2.Dockerfile && alias_image qpod cuda_10.2 cuda

    - name: cuda_11.0
      stage: cuda
      script: build_image qpod cuda_11.0 docker_cuda/cuda11.0.Dockerfile


notifications:
  slack: q-pod:lrzKf5Ff1Ao1MGclzElR23j4
