dist: bionic

env:
  global:
    - REGISTRY_URL: "docker.io"  # or other registry URL
    - REPOSITORY: "$(dirname ${TRAVIS_REPO_SLUG})/qpod"

before_script:
    - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json && sudo service docker restart
    - echo ${REPOSITORY}
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
    - build_image() { docker build --squash -t $1 $2 $(dirname $1); }

stages:
    - base

jobs:
  include:
    - name: "base"
      stage: base
      script:
        - build_image "${REPOSITORY}:${TRAVIS_JOB_NAME}" "docker_base/Dockerfile"
        - docker push "${REPOSITORY}"
