name: qpod-docker-images

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"

  pull_request:
    branches: [ main ]
    paths-ignore:
      - "*.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  qpod_base:
    name: qpod/base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image atom latest docker_atom/Dockerfile && push_image
          build_image base latest docker_base/Dockerfile && alias_image base latest  python latest && push_image

  qpod_core:
    name: qpod/core
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image core latest  docker_core/Dockerfile \
            --build-arg "ARG_PROFILE_PYTHON=base,datascience,mkl,database,nlp,cv,chem,tf2,torch" \
            --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" \
            --build-arg "ARG_PROFILE_NODEJS=base" \
            --build-arg "ARG_PROFILE_JAVA=base,maven" \
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          push_image

  qpod_py-data:
    name: qpod/py-data
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-data latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,mkl,database" && push_image

  qpod_py-chem:
    name: qpod/py-chem
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-chem latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,mkl,chem" && push_image

  qpod_py-std:
    name: qpod/py-std
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-std  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,mkl,database,nlp,cv,chem" && push_image

  qpod_py-jdk:
    name: qpod/py-jdk
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-jdk  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,mkl,database,nlp,cv,chem" --build-arg "ARG_PROFILE_JAVA=base" && push_image

  qpod_r-base:
    name: qpod/r-base
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image r-base latest docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base" && push_image

  qpod_r-std:
    name: qpod/r-std
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image r-std latest docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience" --build-arg "ARG_PROFILE_JAVA=base" && push_image

  qpod_r-latex:
    name: qpod/r-latex
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image r-latex   latest docker_core/Dockerfile \
            --build-arg "ARG_PROFILE_R=base,datascience" \
            --build-arg "ARG_PROFILE_JAVA=base" \
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          push_image

  qpod_r-studio:
    name: qpod/r-studio
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image r-studio  latest docker_core/Dockerfile \
            --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" \
            --build-arg "ARG_PROFILE_JAVA=base" \
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          push_image

  qpod_node:
    name: qpod/node
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image node latest docker_core/Dockerfile --build-arg "ARG_PROFILE_NODEJS=base" && push_image

  qpod_jdk:
    name: qpod/jdk
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image jdk latest docker_core/Dockerfile --build-arg "ARG_PROFILE_JAVA=base"   && push_image

  qpod_julia:
    name: qpod/julia
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image julia latest docker_core/Dockerfile --build-arg "ARG_PROFILE_JULIA=base"  && push_image

  qpod_go:
    name: qpod/go
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image go latest docker_core/Dockerfile --build-arg "ARG_PROFILE_GO=base"     && push_image


  # cuda docker image tags: https://hub.docker.com/r/nvidia/cuda/tags
  # latest cuda supported by torch: https://pytorch.org/get-started/locally/
  # latest cuda supported by tensorflow: https://tensorflow.google.cn/install/source_windows?hl=en#gpu
  qpod_cuda_11_6:
    name: qpod/cuda_11.6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image cuda_11.6 latest docker_atom/Dockerfile --build-arg "BASE_IMG=nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04"
          build_image cuda_11.6 latest docker_base/Dockerfile --build-arg "BASE_IMG=cuda_11.6"
          build_image cuda_11.6 latest docker_cuda/Dockerfile --build-arg "BASE_IMG=cuda_11.6"
          alias_image cuda_11.6 latest cuda latest
          push_image

  qpod_cuda_11_2:
    name: qpod/cuda_11.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image cuda_11.2 latest docker_atom/Dockerfile --build-arg "BASE_IMG=nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04"
          build_image cuda_11.2 latest docker_base/Dockerfile --build-arg "BASE_IMG=cuda_11.2"
          build_image cuda_11.2 latest docker_cuda/Dockerfile --build-arg "BASE_IMG=cuda_11.2"
          alias_image cuda_11.2 latest cuda latest
          push_image

  # For legacy torch/paddle support
  qpod_cuda_10_2:
    name: qpod/cuda_10.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image cuda_10.2 latest docker_atom/Dockerfile --build-arg "BASE_IMG=nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04"
          build_image cuda_10.2 latest docker_base/Dockerfile --build-arg "BASE_IMG=cuda_10.2"
          build_image cuda_10.2 latest docker_cuda/Dockerfile --build-arg "BASE_IMG=cuda_10.2" && push_image

  # cuda_10.0 - for legacy tensorflow 1.15 support
  qpod_cuda_10_0:
    name: qpod/cuda_10.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh        
          build_image cuda_10.0 latest docker_atom/Dockerfile --build-arg "BASE_IMG=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04"
          build_image cuda_10.0 latest docker_base/Dockerfile --build-arg "BASE_IMG=cuda_10.0"
          build_image cuda_10.0 latest docker_cuda/Dockerfile --build-arg "BASE_IMG=cuda_10.0" && push_image


  qpod_tf1:
    name: qpod/tf1
    needs: qpod_cuda_10_0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image tf1-cuda100 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_10.0" --build-arg "ARG_PROFILE_PYTHON=tf1"
          alias_image tf1-cuda100 latest tf1 latest
          push_image

  qpod_tf2:
    name: qpod/tf2
    needs: qpod_cuda_11_2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image tf2-cuda112 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_11.2"  --build-arg "ARG_PROFILE_PYTHON=tf2"
          alias_image tf2-cuda112 latest torch latest
          push_image

  qpod_torch_cuda116:
    name: qpod/torch-cuda116
    needs: qpod_cuda_11_6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image torch-cuda116 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_11.6" --build-arg "ARG_PROFILE_PYTHON=torch"
          alias_image torch-cuda116 latest torch latest
          push_image

  qpod_torch_cuda102:
    name: qpod/torch-cuda102
    needs: qpod_cuda_10_2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image torch-cuda102 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_10.2" --build-arg "ARG_PROFILE_PYTHON=torch"
          push_image

  qpod_paddle_cuda116:
    name: qpod/paddle-cuda116
    needs: qpod_cuda_11_6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image paddle-cuda116 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_11.6" --build-arg "ARG_PROFILE_PYTHON=paddle,mkl"
          alias_image paddle-cuda116 latest paddle latest
          push_image

  qpod_paddle_cuda102:
    name: qpod/paddle-cuda102
    needs: qpod_cuda_10_2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image paddle-cuda102 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_10.2" --build-arg "ARG_PROFILE_PYTHON=paddle,mkl"
          push_image


  qpod_py-nlp-cuda116:
    name: qpod/py-nlp-cuda116
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image py-nlp-cuda116 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_11.6" --build-arg "ARG_PROFILE_PYTHON=datascience,mkl,torch,nlp"
          alias_image py-nlp-cuda116 latest py-nlp latest
          push_image

  qpod_py-nlp-cuda102:
    name: qpod/py-nlp-cuda102
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image py-nlp-cuda102 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_10.2" --build-arg "ARG_PROFILE_PYTHON=datascience,mkl,torch,nlp"
          push_image


  qpod_py-cv:
    name: qpod/py-cv
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh 
          build_image py-cv   latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_11.6" --build-arg "ARG_PROFILE_PYTHON=datascience,mkl,torch,cv"
          push_image


  qpod_core-cuda:
    name: qpod/core-cuda
    needs: qpod_cuda_11_6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh && free_diskspace
          build_image full-cuda-11.6 latest docker_core/Dockerfile \
            --build-arg "BASE_IMG=cuda_11.6" \
            --build-arg "ARG_PROFILE_PYTHON=base,datascience,mkl,database,nlp,cv,chem,tf2,torch" \
            --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" \
            --build-arg "ARG_PROFILE_NODEJS=base" \
            --build-arg "ARG_PROFILE_JAVA=base,maven" \
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          alias_image full-cuda-11.6 latest core-cuda latest && push_image

  qpod_core-dev:
    name: qpod/core-dev
    needs: qpod_core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image core-dev latest docker_dev/Dockerfile \
            --build-arg "ARG_PROFILE_JUPYTER=base,kernels,extensions" \
            --build-arg "ARG_PROFILE_VSCODE=base"
          alias_image core-dev latest full latest && push_image

  qpod_cuda-dev:
    name: qpod/cuda-dev
    needs: qpod_core-cuda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh && free_diskspace
          build_image cuda-dev latest docker_dev/Dockerfile \
            --build-arg "BASE_IMG=core-cuda" \
            --build-arg "ARG_PROFILE_JUPYTER=base,kernels,extensions" \
            --build-arg "ARG_PROFILE_VSCODE=base"
          alias_image cuda-dev latest full-cuda latest && push_image
