name: qpod-docker-images

on:
  pull_request:
    paths-ignore:
      - "*.md"

  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

env:
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  qpod_base:
    name: qpod/base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image atom latest docker_atom/Dockerfile && push_image
          build_image base latest docker_base/Dockerfile && alias_image base latest  python latest && push_image

  # latest cuda supported by torch: https://pytorch.org/get-started/locally/
  qpod_cuda_11_5:
    name: qpod/cuda_11.5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image cuda_11.5 latest docker_atom/Dockerfile --build-arg "BASE_IMG=nvidia/cuda:11.5.2-cudnn8-devel-ubuntu20.04"
          build_image cuda_11.5 latest docker_base/Dockerfile --build-arg "BASE_IMG=cuda_11.5"
          build_image cuda_11.5 latest docker_cuda/Dockerfile --build-arg "BASE_IMG=cuda_11.5"
          alias_image cuda_11.5 latest cuda latest
          push_image

  # For legacy torch support
  qpod_cuda_10_2:
    name: qpod/cuda_10.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image cuda_10.2 latest docker_atom/Dockerfile --build-arg "BASE_IMG=nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04"
          build_image cuda_10.2 latest docker_base/Dockerfile --build-arg "BASE_IMG=cuda_10.2"
          build_image cuda_10.2 latest docker_cuda/Dockerfile --build-arg "BASE_IMG=cuda_10.2" && push_image

  # cuda_10.0 - for legacy tensorflow 1.15 support
  qpod_cuda_10_0:
    name: qpod/cuda_10.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh        
          build_image cuda_10.0 latest docker_atom/Dockerfile --build-arg "BASE_IMG=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04"
          build_image cuda_10.0 latest docker_base/Dockerfile --build-arg "BASE_IMG=cuda_10.0"
          build_image cuda_10.0 latest docker_cuda/Dockerfile --build-arg "BASE_IMG=cuda_10.0" && push_image

  qpod_core:
    name: qpod/core
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image core latest  docker_core/Dockerfile \
            --build-arg "ARG_PROFILE_PYTHON=base,datascience,database,nlp,cv,chem,tf2,torch" \
            --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" \
            --build-arg "ARG_PROFILE_NODEJS=base" \
            --build-arg "ARG_PROFILE_JAVA=base,maven" \
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          push_image

  qpod_py-data:
    name: qpod/py-data
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-data latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database" && push_image

  qpod_py-nlp:
    name: qpod/py-nlp
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-nlp  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,nlp" && push_image

  qpod_py-cv:
    name: qpod/py-cv
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-cv   latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,cv" && push_image

  qpod_py-chem:
    name: qpod/py-chem
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-chem latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,chem" && push_image

  qpod_py-std:
    name: qpod/py-std
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-std  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database,nlp,cv,chem" && push_image

  qpod_py-jdk:
    name: qpod/py-jdk
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image py-jdk  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database,nlp,cv,chem" --build-arg "ARG_PROFILE_JAVA=base" && push_image

  qpod_r-base:
    name: qpod/r-base
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image r-base latest docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base" && push_image

  qpod_r-std:
    name: qpod/r-std
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image r-std latest docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience" --build-arg "ARG_PROFILE_JAVA=base" && push_image

  qpod_r-latex:
    name: qpod/r-latex
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image r-latex   latest docker_core/Dockerfile \
            --build-arg "ARG_PROFILE_R=base,datascience" \
            --build-arg "ARG_PROFILE_JAVA=base" \
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          push_image

  qpod_r-studio:
    name: qpod/r-studio
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image r-studio  latest docker_core/Dockerfile \
            --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" \
            --build-arg "ARG_PROFILE_JAVA=base" \
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          push_image

  qpod_node:
    name: qpod/node
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image node latest docker_core/Dockerfile --build-arg "ARG_PROFILE_NODEJS=base" && push_image

  qpod_jdk:
    name: qpod/jdk
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image jdk latest docker_core/Dockerfile --build-arg "ARG_PROFILE_JAVA=base"   && push_image

  qpod_julia:
    name: qpod/julia
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image julia latest docker_core/Dockerfile --build-arg "ARG_PROFILE_JULIA=base"  && push_image

  qpod_go:
    name: qpod/go
    needs: qpod_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image go latest docker_core/Dockerfile --build-arg "ARG_PROFILE_GO=base"     && push_image

  qpod_tf1:
    name: qpod/tf1
    needs: qpod_cuda_10_0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image tf1-cu100 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_10.0" --build-arg "ARG_PROFILE_PYTHON=tf1"
          alias_image tf1-cu100 latest tf1 latest
          push_image

  qpod_tf2:
    name: qpod/tf2
    needs: qpod_cuda_11_5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image tf2-cu115 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_11.5"  --build-arg "ARG_PROFILE_PYTHON=tf2"
          alias_image tf2-cu115 latest torch latest
          push_image

  qpod_torch_cu115:
    name: qpod/torch-cuda115
    needs: qpod_cuda_11_5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image torch-cu115 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_11.5" --build-arg "ARG_PROFILE_PYTHON=torch"
          alias_image torch-cu115 latest torch latest
          push_image

  qpod_torch_cu102:
    name: qpod/torch-cu102
    needs: qpod_cuda_10_2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image torch-cu102 latest docker_core/Dockerfile --build-arg "BASE_IMG=cuda_10.2" --build-arg "ARG_PROFILE_PYTHON=torch"
          push_image

  qpod_core-cuda:
    name: qpod/core-cuda
    needs: qpod_cuda_11_5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh && free_diskspace
          build_image full-cuda-11.5 latest docker_core/Dockerfile \
            --build-arg "BASE_IMG=cuda_11.5" \
            --build-arg "ARG_PROFILE_PYTHON=base,datascience,database,nlp,cv,chem,tf2,torch" \
            --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" \
            --build-arg "ARG_PROFILE_NODEJS=base" \
            --build-arg "ARG_PROFILE_JAVA=base,maven" \
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          alias_image full-cuda-11.5 latest core-cuda latest && push_image

  qpod_core-dev:
    name: qpod/core-dev
    needs: qpod_core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image core-dev latest docker_dev/Dockerfile \
            --build-arg "ARG_PROFILE_JUPYTER=base,kernels,extensions" \
            --build-arg "ARG_PROFILE_VSCODE=base"
          alias_image core-dev latest full latest && push_image

  qpod_cuda-dev:
    name: qpod/cuda-dev
    needs: qpod_core-cuda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh && free_diskspace
          build_image cuda-dev latest docker_dev/Dockerfile \
            --build-arg "BASE_IMG=core-cuda" \
            --build-arg "ARG_PROFILE_JUPYTER=base,kernels,extensions" \
            --build-arg "ARG_PROFILE_VSCODE=base"
          alias_image cuda-dev latest full-cuda latest && push_image
