name: qpod-docker-images-sync

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"

  pull_request:
    branches: [ main ]
    paths-ignore:
      - "*.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # DOCKER_REGISTRY_USER and DOCKER_REGISTRY_PASSWORD is required for docker image push, they should be set in CI secrets.
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
  DOCKER_MIRROR_REGISTRY_USERNAME: ${{secrets.DOCKER_MIRROR_REGISTRY_USERNAME }}
  DOCKER_MIRROR_REGISTRY_PASSWORD: ${{secrets.DOCKER_MIRROR_REGISTRY_PASSWORD }}
  REGISTRY_URL: "docker.io"   # docker.io or other registry URL, DOCKER_REGISTRY_USER/DOCKER_REGISTRY_PASSWORD to be set in CI env.
  BUILDKIT_PROGRESS: "plain"  # Full logs for CI build.


jobs:
  qpod_base:
    name: qpod/base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          source devops/image-syncer/setup-sync.sh
          python devops/image-syncer/run-sync.py qpod/base
